version = 0.1

[default.deploy.parameters]
stack_name = "assets-api"
resolve_s3 = true
s3_prefix = "assets-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["ICAAAssets=197461532156.dkr.ecr.us-east-1.amazonaws.com/assetsapiab9b273c/icaaassets7139eb54repo"]

[default.global.parameters]
region = "us-east-1"
