//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	GoogleBearerAuthScopes = "googleBearerAuth.Scopes"
	GoogleCookieAuthScopes = "googleCookieAuth.Scopes"
)

// Defines values for AssetType.
const (
	AssetTypeFile   AssetType = "file"
	AssetTypeFolder AssetType = "folder"
)

// Defines values for ErrorCode.
const (
	AlreadyExists        ErrorCode = "AlreadyExists"
	AssetNotUploaded     ErrorCode = "AssetNotUploaded"
	AuthError            ErrorCode = "AuthError"
	EmptyBody            ErrorCode = "EmptyBody"
	FileTooLarge         ErrorCode = "FileTooLarge"
	FolderNotEmpty       ErrorCode = "FolderNotEmpty"
	InputValidationError ErrorCode = "InputValidationError"
	InternalError        ErrorCode = "InternalError"
	InvalidBody          ErrorCode = "InvalidBody"
	InvalidCursor        ErrorCode = "InvalidCursor"
	LimitOutOfBounds     ErrorCode = "LimitOutOfBounds"
	NotAFile             ErrorCode = "NotAFile"
	NotFound             ErrorCode = "NotFound"
	ParentFolderNotFound ErrorCode = "ParentFolderNotFound"
	VersionConflict      ErrorCode = "VersionConflict"
)

// Defines values for FileStatus.
const (
	Confirmed FileStatus = "confirmed"
	Pending   FileStatus = "pending"
)

// Asset defines model for Asset.
type Asset struct {
	union json.RawMessage
}

// AssetType defines model for AssetType.
type AssetType string

// CreateFolderRequest defines model for CreateFolderRequest.
type CreateFolderRequest struct {
	// Description Optional description of the folder
	Description *string `json:"description,omitempty"`

	// Name Name of the folder to create
	Name string `json:"name"`

	// Path Parent folder path (use "/" for root)
	Path string `json:"path"`
}

// Error defines model for Error.
type Error struct {
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// File defines model for File.
type File struct {
	ContentType string     `json:"contentType"`
	CreatedAt   *time.Time `json:"createdAt,omitempty"`

	// CreatedBy Email of the admin who uploaded the file
	CreatedBy   *string             `json:"createdBy,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	Name        string              `json:"name"`

	// Path Parent folder path
	Path string `json:"path"`

	// Size File size in bytes
	Size   int64      `json:"size"`
	Status FileStatus `json:"status"`
	Type   AssetType  `json:"type"`

	// Url CDN URL for the file
	Url string `json:"url"`
}

// FileStatus defines model for FileStatus.
type FileStatus string

// Folder defines model for Folder.
type Folder struct {
	// ContentCount Number of items (files and folders) directly in this folder
	ContentCount int        `json:"contentCount"`
	CreatedAt    *time.Time `json:"createdAt,omitempty"`

	// CreatedBy Email of the admin who created the folder
	CreatedBy   *string             `json:"createdBy,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	Name        string              `json:"name"`

	// Path Parent folder path
	Path string    `json:"path"`
	Type AssetType `json:"type"`
}

// UploadRequest defines model for UploadRequest.
type UploadRequest struct {
	// ContentType MIME type of the file
	ContentType string `json:"contentType"`

	// Description Optional description of the file
	Description *string `json:"description,omitempty"`

	// FileName Original file name
	FileName string `json:"fileName"`

	// Path Parent folder path where the file will be stored
	Path string `json:"path"`
}

// UploadResponse defines model for UploadResponse.
type UploadResponse struct {
	// ExpiresAt When the presigned URL expires
	ExpiresAt time.Time `json:"expiresAt"`

	// FileId ID of the file (use this to confirm the upload)
	FileId openapi_types.UUID `json:"fileId"`

	// UploadUrl Presigned URL to upload the file to
	UploadUrl string `json:"uploadUrl"`
}

// GetAssetsV1Params defines parameters for GetAssetsV1.
type GetAssetsV1Params struct {
	// Path Path to list assets from (use "/" for root)
	Path string `form:"path" json:"path"`

	// Cursor Cursor for pagination
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Max number of assets to fetch
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostAssetsV1FoldersJSONRequestBody defines body for PostAssetsV1Folders for application/json ContentType.
type PostAssetsV1FoldersJSONRequestBody = CreateFolderRequest

// PostAssetsV1UploadUrlJSONRequestBody defines body for PostAssetsV1UploadUrl for application/json ContentType.
type PostAssetsV1UploadUrlJSONRequestBody = UploadRequest

// AsFile returns the union data inside the Asset as a File
func (t Asset) AsFile() (File, error) {
	var body File
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFile overwrites any union data inside the Asset as the provided File
func (t *Asset) FromFile(v File) error {
	v.Type = "file"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFile performs a merge with any union data inside the Asset, using the provided File
func (t *Asset) MergeFile(v File) error {
	v.Type = "file"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFolder returns the union data inside the Asset as a Folder
func (t Asset) AsFolder() (Folder, error) {
	var body Folder
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFolder overwrites any union data inside the Asset as the provided Folder
func (t *Asset) FromFolder(v Folder) error {
	v.Type = "folder"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFolder performs a merge with any union data inside the Asset, using the provided Folder
func (t *Asset) MergeFolder(v Folder) error {
	v.Type = "folder"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Asset) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Asset) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "file":
		return t.AsFile()
	case "folder":
		return t.AsFolder()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Asset) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Asset) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all assets at a path
	// (GET /assets/v1)
	GetAssetsV1(w http.ResponseWriter, r *http.Request, params GetAssetsV1Params)
	// Create a folder
	// (POST /assets/v1/folders)
	PostAssetsV1Folders(w http.ResponseWriter, r *http.Request)
	// Get a presigned upload URL
	// (POST /assets/v1/upload-url)
	PostAssetsV1UploadUrl(w http.ResponseWriter, r *http.Request)
	// Delete an asset
	// (DELETE /assets/v1/{id})
	DeleteAssetsV1Id(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Get an asset
	// (GET /assets/v1/{id})
	GetAssetsV1Id(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Confirm file upload
	// (POST /assets/v1/{id}/confirm)
	PostAssetsV1IdConfirm(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAssetsV1 operation middleware
func (siw *ServerInterfaceWrapper) GetAssetsV1(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAssetsV1Params

	// ------------- Required query parameter "path" -------------

	if paramValue := r.URL.Query().Get("path"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", r.URL.Query(), &params.Cursor)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAssetsV1(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAssetsV1Folders operation middleware
func (siw *ServerInterfaceWrapper) PostAssetsV1Folders(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, GoogleCookieAuthScopes, []string{"admin"})

	ctx = context.WithValue(ctx, GoogleBearerAuthScopes, []string{"admin"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAssetsV1Folders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAssetsV1UploadUrl operation middleware
func (siw *ServerInterfaceWrapper) PostAssetsV1UploadUrl(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, GoogleCookieAuthScopes, []string{"admin"})

	ctx = context.WithValue(ctx, GoogleBearerAuthScopes, []string{"admin"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAssetsV1UploadUrl(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAssetsV1Id operation middleware
func (siw *ServerInterfaceWrapper) DeleteAssetsV1Id(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, GoogleCookieAuthScopes, []string{"admin"})

	ctx = context.WithValue(ctx, GoogleBearerAuthScopes, []string{"admin"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAssetsV1Id(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAssetsV1Id operation middleware
func (siw *ServerInterfaceWrapper) GetAssetsV1Id(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAssetsV1Id(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAssetsV1IdConfirm operation middleware
func (siw *ServerInterfaceWrapper) PostAssetsV1IdConfirm(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, GoogleCookieAuthScopes, []string{"admin"})

	ctx = context.WithValue(ctx, GoogleBearerAuthScopes, []string{"admin"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAssetsV1IdConfirm(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/assets/v1", wrapper.GetAssetsV1)
	m.HandleFunc("POST "+options.BaseURL+"/assets/v1/folders", wrapper.PostAssetsV1Folders)
	m.HandleFunc("POST "+options.BaseURL+"/assets/v1/upload-url", wrapper.PostAssetsV1UploadUrl)
	m.HandleFunc("DELETE "+options.BaseURL+"/assets/v1/{id}", wrapper.DeleteAssetsV1Id)
	m.HandleFunc("GET "+options.BaseURL+"/assets/v1/{id}", wrapper.GetAssetsV1Id)
	m.HandleFunc("POST "+options.BaseURL+"/assets/v1/{id}/confirm", wrapper.PostAssetsV1IdConfirm)

	return m
}

type GetAssetsV1RequestObject struct {
	Params GetAssetsV1Params
}

type GetAssetsV1ResponseObject interface {
	VisitGetAssetsV1Response(w http.ResponseWriter) error
}

type GetAssetsV1200JSONResponse struct {
	Cursor      *string `json:"cursor,omitempty"`
	Data        []Asset `json:"data"`
	HasNextPage bool    `json:"hasNextPage"`
}

func (response GetAssetsV1200JSONResponse) VisitGetAssetsV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAssetsV1400JSONResponse Error

func (response GetAssetsV1400JSONResponse) VisitGetAssetsV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetAssetsV1500JSONResponse Error

func (response GetAssetsV1500JSONResponse) VisitGetAssetsV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1FoldersRequestObject struct {
	Body *PostAssetsV1FoldersJSONRequestBody
}

type PostAssetsV1FoldersResponseObject interface {
	VisitPostAssetsV1FoldersResponse(w http.ResponseWriter) error
}

type PostAssetsV1Folders201JSONResponse struct {
	Folder Folder `json:"folder"`
}

func (response PostAssetsV1Folders201JSONResponse) VisitPostAssetsV1FoldersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1Folders400JSONResponse Error

func (response PostAssetsV1Folders400JSONResponse) VisitPostAssetsV1FoldersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1Folders401JSONResponse Error

func (response PostAssetsV1Folders401JSONResponse) VisitPostAssetsV1FoldersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1Folders404JSONResponse Error

func (response PostAssetsV1Folders404JSONResponse) VisitPostAssetsV1FoldersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1Folders409JSONResponse Error

func (response PostAssetsV1Folders409JSONResponse) VisitPostAssetsV1FoldersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1Folders500JSONResponse Error

func (response PostAssetsV1Folders500JSONResponse) VisitPostAssetsV1FoldersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1UploadUrlRequestObject struct {
	Body *PostAssetsV1UploadUrlJSONRequestBody
}

type PostAssetsV1UploadUrlResponseObject interface {
	VisitPostAssetsV1UploadUrlResponse(w http.ResponseWriter) error
}

type PostAssetsV1UploadUrl200JSONResponse UploadResponse

func (response PostAssetsV1UploadUrl200JSONResponse) VisitPostAssetsV1UploadUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1UploadUrl400JSONResponse Error

func (response PostAssetsV1UploadUrl400JSONResponse) VisitPostAssetsV1UploadUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1UploadUrl401JSONResponse Error

func (response PostAssetsV1UploadUrl401JSONResponse) VisitPostAssetsV1UploadUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1UploadUrl404JSONResponse Error

func (response PostAssetsV1UploadUrl404JSONResponse) VisitPostAssetsV1UploadUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1UploadUrl500JSONResponse Error

func (response PostAssetsV1UploadUrl500JSONResponse) VisitPostAssetsV1UploadUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAssetsV1IdRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeleteAssetsV1IdResponseObject interface {
	VisitDeleteAssetsV1IdResponse(w http.ResponseWriter) error
}

type DeleteAssetsV1Id204Response struct {
}

func (response DeleteAssetsV1Id204Response) VisitDeleteAssetsV1IdResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteAssetsV1Id400JSONResponse Error

func (response DeleteAssetsV1Id400JSONResponse) VisitDeleteAssetsV1IdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAssetsV1Id401JSONResponse Error

func (response DeleteAssetsV1Id401JSONResponse) VisitDeleteAssetsV1IdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAssetsV1Id404JSONResponse Error

func (response DeleteAssetsV1Id404JSONResponse) VisitDeleteAssetsV1IdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAssetsV1Id500JSONResponse Error

func (response DeleteAssetsV1Id500JSONResponse) VisitDeleteAssetsV1IdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetAssetsV1IdRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetAssetsV1IdResponseObject interface {
	VisitGetAssetsV1IdResponse(w http.ResponseWriter) error
}

type GetAssetsV1Id200JSONResponse struct {
	Asset Asset `json:"asset"`
}

func (response GetAssetsV1Id200JSONResponse) VisitGetAssetsV1IdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAssetsV1Id400JSONResponse Error

func (response GetAssetsV1Id400JSONResponse) VisitGetAssetsV1IdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetAssetsV1Id404JSONResponse Error

func (response GetAssetsV1Id404JSONResponse) VisitGetAssetsV1IdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetAssetsV1Id500JSONResponse Error

func (response GetAssetsV1Id500JSONResponse) VisitGetAssetsV1IdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1IdConfirmRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type PostAssetsV1IdConfirmResponseObject interface {
	VisitPostAssetsV1IdConfirmResponse(w http.ResponseWriter) error
}

type PostAssetsV1IdConfirm200JSONResponse struct {
	File File `json:"file"`
}

func (response PostAssetsV1IdConfirm200JSONResponse) VisitPostAssetsV1IdConfirmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1IdConfirm400JSONResponse Error

func (response PostAssetsV1IdConfirm400JSONResponse) VisitPostAssetsV1IdConfirmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1IdConfirm401JSONResponse Error

func (response PostAssetsV1IdConfirm401JSONResponse) VisitPostAssetsV1IdConfirmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1IdConfirm404JSONResponse Error

func (response PostAssetsV1IdConfirm404JSONResponse) VisitPostAssetsV1IdConfirmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1IdConfirm409JSONResponse Error

func (response PostAssetsV1IdConfirm409JSONResponse) VisitPostAssetsV1IdConfirmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1IdConfirm500JSONResponse Error

func (response PostAssetsV1IdConfirm500JSONResponse) VisitPostAssetsV1IdConfirmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get all assets at a path
	// (GET /assets/v1)
	GetAssetsV1(ctx context.Context, request GetAssetsV1RequestObject) (GetAssetsV1ResponseObject, error)
	// Create a folder
	// (POST /assets/v1/folders)
	PostAssetsV1Folders(ctx context.Context, request PostAssetsV1FoldersRequestObject) (PostAssetsV1FoldersResponseObject, error)
	// Get a presigned upload URL
	// (POST /assets/v1/upload-url)
	PostAssetsV1UploadUrl(ctx context.Context, request PostAssetsV1UploadUrlRequestObject) (PostAssetsV1UploadUrlResponseObject, error)
	// Delete an asset
	// (DELETE /assets/v1/{id})
	DeleteAssetsV1Id(ctx context.Context, request DeleteAssetsV1IdRequestObject) (DeleteAssetsV1IdResponseObject, error)
	// Get an asset
	// (GET /assets/v1/{id})
	GetAssetsV1Id(ctx context.Context, request GetAssetsV1IdRequestObject) (GetAssetsV1IdResponseObject, error)
	// Confirm file upload
	// (POST /assets/v1/{id}/confirm)
	PostAssetsV1IdConfirm(ctx context.Context, request PostAssetsV1IdConfirmRequestObject) (PostAssetsV1IdConfirmResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetAssetsV1 operation middleware
func (sh *strictHandler) GetAssetsV1(w http.ResponseWriter, r *http.Request, params GetAssetsV1Params) {
	var request GetAssetsV1RequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAssetsV1(ctx, request.(GetAssetsV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAssetsV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAssetsV1ResponseObject); ok {
		if err := validResponse.VisitGetAssetsV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAssetsV1Folders operation middleware
func (sh *strictHandler) PostAssetsV1Folders(w http.ResponseWriter, r *http.Request) {
	var request PostAssetsV1FoldersRequestObject

	var body PostAssetsV1FoldersJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAssetsV1Folders(ctx, request.(PostAssetsV1FoldersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAssetsV1Folders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAssetsV1FoldersResponseObject); ok {
		if err := validResponse.VisitPostAssetsV1FoldersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAssetsV1UploadUrl operation middleware
func (sh *strictHandler) PostAssetsV1UploadUrl(w http.ResponseWriter, r *http.Request) {
	var request PostAssetsV1UploadUrlRequestObject

	var body PostAssetsV1UploadUrlJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAssetsV1UploadUrl(ctx, request.(PostAssetsV1UploadUrlRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAssetsV1UploadUrl")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAssetsV1UploadUrlResponseObject); ok {
		if err := validResponse.VisitPostAssetsV1UploadUrlResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteAssetsV1Id operation middleware
func (sh *strictHandler) DeleteAssetsV1Id(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DeleteAssetsV1IdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteAssetsV1Id(ctx, request.(DeleteAssetsV1IdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteAssetsV1Id")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteAssetsV1IdResponseObject); ok {
		if err := validResponse.VisitDeleteAssetsV1IdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAssetsV1Id operation middleware
func (sh *strictHandler) GetAssetsV1Id(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetAssetsV1IdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAssetsV1Id(ctx, request.(GetAssetsV1IdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAssetsV1Id")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAssetsV1IdResponseObject); ok {
		if err := validResponse.VisitGetAssetsV1IdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAssetsV1IdConfirm operation middleware
func (sh *strictHandler) PostAssetsV1IdConfirm(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request PostAssetsV1IdConfirmRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAssetsV1IdConfirm(ctx, request.(PostAssetsV1IdConfirmRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAssetsV1IdConfirm")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAssetsV1IdConfirmResponseObject); ok {
		if err := validResponse.VisitPostAssetsV1IdConfirmResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabW/bOBL+KwTvPrSAYjtvvdbA4s5Jk9R7aRK0SXrXbrCgpbHNXYlUSSqJE/i/H4ak",
	"3iwldtr0BbnNh0AWqZnhcObhMyPd0lAmqRQgjKb9W6rDKSTMXg60BoMXEdeh4gkXzEiFNxKWplxM8HLM",
	"Y6B9+rduKabrZXT3cSygYxlHoO6c5EbnAU2VTEGZ2RFLUKSZpYC3pYDjMe1/uqV/VzC+V9c8WDLJ67qY",
	"B251p6ijf0tBZAntf3KrKSy+CChcsyS1K/RD1qo+1UahA+YB3VXADDjJ7+BzBtr6zC+Gg3VlBOjB1HAp",
	"Gj/psb1gMancJnJMzBSIt6RqyDBhE9BkLJWdMZUJpGwCJGRKZhpiGtCEXR+CmJgp7a/3er0Wq4X18aIl",
	"6Pm6ZmIkCe0Kaza069rY3g5owkWhu0VxynBkUfEJUyBMrhPnkGeZBvIb7f5G7VKVlOZ5zYYut45o7sk8",
	"oAo+Z1xBhHtqNfoVXxST5egPCA1atKeUi+r6loUysh66L57so7s4cR7QBLRmExdOhZEDQTIB1ymEBiIC",
	"OJ/IMMyUgqiz1HRrQyn5Tut3va15GA+FASVY7JYW0EOecHOcmePxjsxEhD4biksW82g3U9pOOZJmH8do",
	"QPeS1Mx2ZDQrp/lfg1gBi2Z711wbJyTNzDlOYLiRubpBZqbFNabZkTRnaSxZBCgfU/VUykOmJrg6lzpH",
	"0li9NPDBUNzOzTqSZuAR5RyU5lLsSjGOeWgqjikDzU5t2VVhQJR5X2yUDaZuKiaN9GmR7TIiGpi6jI3e",
	"xvZa7+Xa+qvT9Zf9rRf97c3O+svtjxZRVMIM7dOIGVgzPMFloDOPRTyjfaMyuFvPzqyZMXsJ43GeqyxK",
	"uCBXU0ky72aXws5bpYF23r94yFjnSqo4WsWGBegqhb1lXJApKElGTAhQX4lIPKqL7/m/tZZ/+V/VsVnG",
	"V1pPjnylJlzDmltDpxEAj4lpbfDVrTipIVjzmxaUxsgmOES4IKOZsRhYCF7vbb3c/seLime4MC+2SvFc",
	"GJi4E1cbZjK9DOVQ33s3c55Luf+J8mydBzRTcXMNu6+PyNm7wyJmGqE6NSbV/W6XoSjdKWO2y0bh+sbm",
	"Uuy0ozasgtoRENQwwPvYWVk4pJrh1SxsA+CKdyoInIKIuI2lUIoxVwlEdTpR3m7DLs+Y7kCvXZkJ03J6",
	"Z8kIFGICN5Bo8gydqgkTkQ9C/ZxEXEFo4hmGjply3UIwttsi5edFPP/EXWzpUSHvUajXjwO6b8/aViNo",
	"DwaRh6a2S5CHZLGjJ3fy9wXaUHfD2+HbPYISC+q8CGYPIhdfXissqn3kExrlH7XWDceKTzhahVOI34sf",
	"cMCSqykoKJxBrngckxEQbaSySPuQ47e9jCicUD9H7ospnUqhW7goXKdcgR60QPmHKQi7jFSB5hMBkT0t",
	"/RO1hVQh+NUKENy6rcOoacPwdTWwXD1mjwwsCd3pZUcd5azXZl+IaQ3bnOyzNgZxUvOMyalvabCRrYQC",
	"j4I1zyr0Zocl7EYKdqU7oUw8t/jnf9YGyc1ap7O8QvPOq1oaVDa2GRbIuiDMFDez9wh0LhQmUk5i2AGm",
	"QGH1hPdG9td+7qJfP5wiQbHP0L4fLe3D5aHHnKRdKf/kkEviwhIOvJVDZZ8eHB8fHO79Pjg7ffO7k+0l",
	"sZT/G2Z0jqZyMZZN1w8EGZwMLZokTLAJFxPiPNrKOXLUGe4OBuQKRpobsJ7lxp2qeH/gnh+cDGlAL119",
	"R/t0vdPr9GwXKAXBUk77dNPecqBgnec5Yvdy3boSWvLpHRjF4RItIzHXBiObxfF9VjNjjdYphHzMIcrP",
	"N8xgW+1iztADMM7y83VrkmIJGFDa9qsW4cpMMU6tfq94rGRyV6fD7trnDNSs3DRvQxmB7ux3R2b9sO+2",
	"xW6Dhtvy36pNcR/twu7QHeatgjZt/914lX3c/HUavXmrh2/iy+j9TjLaPM8+7u702MHZ5OOH/Zvo4Hw2",
	"PDgXH69++WUV496yayIKTus9ZiQZgwmndxgZ84Sbmo0RjFkWG9rf6FXgAH8k7JonSNftOZxw4X81+e/8",
	"An3ucNyG3EavV6EFeMnSNOah9V/3D+2O7tKIBTbhPPnIDgwQ5q02S/9XolclF6NMKTbD31Omj+DanCz2",
	"smo0cyRlDEw08NCaUJfRgoGLLIcOyqx0yIyGbD3QyUs7dW2ad1hElKN9Vun291B6Jv4U8koQDeoSlGsL",
	"dmpnA+1/ugiozpKEqZnDmSpgMUOYAyR8qATArocvG3NStyCha1cjDgq4yrlTK9Z1yMAWWVLEs04D+E6k",
	"LpBv3yt1oQDa2HbhY3mxrcHe4lM3wZWDSIojMIzHuoGW80Yqr39FKo+LSn2V9w6L5KF4zbA0Qaqrg4jo",
	"LAxB63EW4978qFzZeqDrvjBXWGamUvEbiLzWrW+vtV5bCImXmcgNePXtDfAbzlzHnYBtuf9kCHXbwjY/",
	"uY4LvcDzvElry+EavLkcJyzv4CygmiPXa76T2A5s78BkSiCw1Wsm5DbueUtTXW1QtMGMJO83a0hHTrHs",
	"qm1/kmnjduB+HDyr1ADfAgnrTYq2XXMlkNf9AAjsPbqNvuhtS61ie3zFhruE1NvuNxm+/gvQvjOgPUVE",
	"sYSpAgVlrC2Cyy2P5g5OYjAtza3X9j5hwgfoaIYxWoMMO8XDi3Ow7TyNGY8JHxNuiDZ4Az3MOIKUmBFX",
	"c0pFdDbytK0JL055DjDDaFmRWTZtrLF5lVTtkvap7x8vryEfp43TUj1ttTQVrHPdJvwEBIc8g86kE1QT",
	"BpLUzJ4/daBw+/D0AWIhrW3vrK11hEAihc8n1ykitmWCcfHcocF9baEnk7Nf0/Fg+adkK3QkFook9+gq",
	"NdJp4cEfxx/+7xO0eQgXCdY8drv+PcI97Qo3QRMztT0Pm35TpskIQFS+dmnQ+HuJ+jDycldPTf9y7cll",
	"5th/JrX828qWNx+rtS5wy4rPHX6ik92+q5SmjKIZmACx3UE913bUxdyTP/b3c2985z6H/5TPBkjMw/yE",
	"vWKaJDJy3cjRjDAhzRRUvofPn24nxL9ZtV5wkemsWqbtLjVOvjW+9a2UklEW2o6pm+S/hap8gZXy6udX",
	"tPmi5lCG9ouEyzYR/W43xvGp1Ka/2ev1unR+Mf9fAAAA///+XXP3dy4AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
