//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	GoogleBearerAuthScopes = "googleBearerAuth.Scopes"
	GoogleCookieAuthScopes = "googleCookieAuth.Scopes"
)

// Defines values for AssetType.
const (
	File   AssetType = "file"
	Folder AssetType = "folder"
)

// Defines values for ErrorCode.
const (
	AlreadyExists        ErrorCode = "AlreadyExists"
	AssetNotUploaded     ErrorCode = "AssetNotUploaded"
	AuthError            ErrorCode = "AuthError"
	EmptyBody            ErrorCode = "EmptyBody"
	FileTooLarge         ErrorCode = "FileTooLarge"
	FolderNotEmpty       ErrorCode = "FolderNotEmpty"
	InputValidationError ErrorCode = "InputValidationError"
	InternalError        ErrorCode = "InternalError"
	InvalidBody          ErrorCode = "InvalidBody"
	InvalidCursor        ErrorCode = "InvalidCursor"
	LimitOutOfBounds     ErrorCode = "LimitOutOfBounds"
	NotAFile             ErrorCode = "NotAFile"
	NotFound             ErrorCode = "NotFound"
	ParentFolderNotFound ErrorCode = "ParentFolderNotFound"
	VersionConflict      ErrorCode = "VersionConflict"
)

// Defines values for FileStatus.
const (
	Confirmed FileStatus = "confirmed"
	Pending   FileStatus = "pending"
)

// AdminAsset defines model for AdminAsset.
type AdminAsset struct {
	union json.RawMessage
}

// AdminFile defines model for AdminFile.
type AdminFile struct {
	ContentType string     `json:"contentType"`
	CreatedAt   *time.Time `json:"createdAt,omitempty"`

	// CreatedBy Email of the admin who uploaded the file
	CreatedBy   *string             `json:"createdBy,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	Name        string              `json:"name"`

	// Path Parent folder path
	Path string `json:"path"`

	// Size File size in bytes
	Size   int64      `json:"size"`
	Status FileStatus `json:"status"`
	Type   AssetType  `json:"type"`

	// Url CDN URL for the file
	Url string `json:"url"`
}

// AdminFolder defines model for AdminFolder.
type AdminFolder struct {
	// ContentCount Number of items (files and folders) directly in this folder
	ContentCount int        `json:"contentCount"`
	CreatedAt    *time.Time `json:"createdAt,omitempty"`

	// CreatedBy Email of the admin who created the folder
	CreatedBy   *string             `json:"createdBy,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	Name        string              `json:"name"`

	// Path Parent folder path
	Path string    `json:"path"`
	Type AssetType `json:"type"`
}

// AssetType defines model for AssetType.
type AssetType string

// CreateFolderRequest defines model for CreateFolderRequest.
type CreateFolderRequest struct {
	// Description Optional description of the folder
	Description *string `json:"description,omitempty"`

	// Name Name of the folder to create
	Name string `json:"name"`

	// Path Parent folder path (use "/" for root)
	Path string `json:"path"`
}

// Error defines model for Error.
type Error struct {
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// FileStatus defines model for FileStatus.
type FileStatus string

// PublicAsset defines model for PublicAsset.
type PublicAsset struct {
	union json.RawMessage
}

// PublicFile defines model for PublicFile.
type PublicFile struct {
	ContentType string  `json:"contentType"`
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`

	// Path Parent folder path
	Path string `json:"path"`

	// Size File size in bytes
	Size int64     `json:"size"`
	Type AssetType `json:"type"`

	// Url CDN URL for the file
	Url string `json:"url"`
}

// PublicFolder defines model for PublicFolder.
type PublicFolder struct {
	// ContentCount Number of items (files and folders) directly in this folder
	ContentCount int     `json:"contentCount"`
	Description  *string `json:"description,omitempty"`
	Name         string  `json:"name"`

	// Path Parent folder path
	Path string    `json:"path"`
	Type AssetType `json:"type"`
}

// UploadRequest defines model for UploadRequest.
type UploadRequest struct {
	// ContentType MIME type of the file
	ContentType string `json:"contentType"`

	// Description Optional description of the file
	Description *string `json:"description,omitempty"`

	// FileName Original file name
	FileName string `json:"fileName"`

	// Path Parent folder path where the file will be stored
	Path string `json:"path"`
}

// UploadResponse defines model for UploadResponse.
type UploadResponse struct {
	// ExpiresAt When the presigned URL expires
	ExpiresAt time.Time `json:"expiresAt"`

	// FileId ID of the file (use this to confirm the upload)
	FileId openapi_types.UUID `json:"fileId"`

	// FormFields Form fields that must be included in the multipart/form-data POST request. The file itself must be added last with the field name 'file'.
	FormFields map[string]string `json:"formFields"`

	// UploadUrl Presigned POST URL to upload the file to
	UploadUrl string `json:"uploadUrl"`
}

// GetAssetsV1Params defines parameters for GetAssetsV1.
type GetAssetsV1Params struct {
	// Path Path to list assets from (use "/" for root)
	Path string `form:"path" json:"path"`

	// Cursor Cursor for pagination
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Max number of assets to fetch
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// DeleteAssetsV1ByPathParams defines parameters for DeleteAssetsV1ByPath.
type DeleteAssetsV1ByPathParams struct {
	// Path Full path to the asset (e.g., "/foo/bar.txt")
	Path string `form:"path" json:"path"`
}

// GetAssetsV1ByPathParams defines parameters for GetAssetsV1ByPath.
type GetAssetsV1ByPathParams struct {
	// Path Full path to the asset (e.g., "/foo/bar.txt" or "/" for root)
	Path string `form:"path" json:"path"`
}

// PostAssetsV1ByPathConfirmParams defines parameters for PostAssetsV1ByPathConfirm.
type PostAssetsV1ByPathConfirmParams struct {
	// Path Full path to the file (e.g., "/foo/bar.txt")
	Path string `form:"path" json:"path"`
}

// PostAssetsV1FoldersJSONRequestBody defines body for PostAssetsV1Folders for application/json ContentType.
type PostAssetsV1FoldersJSONRequestBody = CreateFolderRequest

// PostAssetsV1UploadUrlJSONRequestBody defines body for PostAssetsV1UploadUrl for application/json ContentType.
type PostAssetsV1UploadUrlJSONRequestBody = UploadRequest

// AsAdminFile returns the union data inside the AdminAsset as a AdminFile
func (t AdminAsset) AsAdminFile() (AdminFile, error) {
	var body AdminFile
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAdminFile overwrites any union data inside the AdminAsset as the provided AdminFile
func (t *AdminAsset) FromAdminFile(v AdminFile) error {
	v.Type = "file"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAdminFile performs a merge with any union data inside the AdminAsset, using the provided AdminFile
func (t *AdminAsset) MergeAdminFile(v AdminFile) error {
	v.Type = "file"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAdminFolder returns the union data inside the AdminAsset as a AdminFolder
func (t AdminAsset) AsAdminFolder() (AdminFolder, error) {
	var body AdminFolder
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAdminFolder overwrites any union data inside the AdminAsset as the provided AdminFolder
func (t *AdminAsset) FromAdminFolder(v AdminFolder) error {
	v.Type = "folder"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAdminFolder performs a merge with any union data inside the AdminAsset, using the provided AdminFolder
func (t *AdminAsset) MergeAdminFolder(v AdminFolder) error {
	v.Type = "folder"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AdminAsset) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t AdminAsset) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "file":
		return t.AsAdminFile()
	case "folder":
		return t.AsAdminFolder()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t AdminAsset) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AdminAsset) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsPublicFile returns the union data inside the PublicAsset as a PublicFile
func (t PublicAsset) AsPublicFile() (PublicFile, error) {
	var body PublicFile
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPublicFile overwrites any union data inside the PublicAsset as the provided PublicFile
func (t *PublicAsset) FromPublicFile(v PublicFile) error {
	v.Type = "file"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePublicFile performs a merge with any union data inside the PublicAsset, using the provided PublicFile
func (t *PublicAsset) MergePublicFile(v PublicFile) error {
	v.Type = "file"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPublicFolder returns the union data inside the PublicAsset as a PublicFolder
func (t PublicAsset) AsPublicFolder() (PublicFolder, error) {
	var body PublicFolder
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPublicFolder overwrites any union data inside the PublicAsset as the provided PublicFolder
func (t *PublicAsset) FromPublicFolder(v PublicFolder) error {
	v.Type = "folder"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePublicFolder performs a merge with any union data inside the PublicAsset, using the provided PublicFolder
func (t *PublicAsset) MergePublicFolder(v PublicFolder) error {
	v.Type = "folder"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PublicAsset) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t PublicAsset) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "file":
		return t.AsPublicFile()
	case "folder":
		return t.AsPublicFolder()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t PublicAsset) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PublicAsset) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all assets at a path
	// (GET /assets/v1)
	GetAssetsV1(w http.ResponseWriter, r *http.Request, params GetAssetsV1Params)
	// Delete an asset
	// (DELETE /assets/v1/by-path)
	DeleteAssetsV1ByPath(w http.ResponseWriter, r *http.Request, params DeleteAssetsV1ByPathParams)
	// Get an asset
	// (GET /assets/v1/by-path)
	GetAssetsV1ByPath(w http.ResponseWriter, r *http.Request, params GetAssetsV1ByPathParams)
	// Confirm file upload
	// (POST /assets/v1/by-path/confirm)
	PostAssetsV1ByPathConfirm(w http.ResponseWriter, r *http.Request, params PostAssetsV1ByPathConfirmParams)
	// Create a folder
	// (POST /assets/v1/folders)
	PostAssetsV1Folders(w http.ResponseWriter, r *http.Request)
	// Get a presigned upload URL
	// (POST /assets/v1/upload-url)
	PostAssetsV1UploadUrl(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAssetsV1 operation middleware
func (siw *ServerInterfaceWrapper) GetAssetsV1(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAssetsV1Params

	// ------------- Required query parameter "path" -------------

	if paramValue := r.URL.Query().Get("path"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", r.URL.Query(), &params.Cursor)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAssetsV1(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAssetsV1ByPath operation middleware
func (siw *ServerInterfaceWrapper) DeleteAssetsV1ByPath(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, GoogleCookieAuthScopes, []string{"admin"})

	ctx = context.WithValue(ctx, GoogleBearerAuthScopes, []string{"admin"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteAssetsV1ByPathParams

	// ------------- Required query parameter "path" -------------

	if paramValue := r.URL.Query().Get("path"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAssetsV1ByPath(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAssetsV1ByPath operation middleware
func (siw *ServerInterfaceWrapper) GetAssetsV1ByPath(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAssetsV1ByPathParams

	// ------------- Required query parameter "path" -------------

	if paramValue := r.URL.Query().Get("path"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAssetsV1ByPath(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAssetsV1ByPathConfirm operation middleware
func (siw *ServerInterfaceWrapper) PostAssetsV1ByPathConfirm(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, GoogleCookieAuthScopes, []string{"admin"})

	ctx = context.WithValue(ctx, GoogleBearerAuthScopes, []string{"admin"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params PostAssetsV1ByPathConfirmParams

	// ------------- Required query parameter "path" -------------

	if paramValue := r.URL.Query().Get("path"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAssetsV1ByPathConfirm(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAssetsV1Folders operation middleware
func (siw *ServerInterfaceWrapper) PostAssetsV1Folders(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, GoogleCookieAuthScopes, []string{"admin"})

	ctx = context.WithValue(ctx, GoogleBearerAuthScopes, []string{"admin"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAssetsV1Folders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAssetsV1UploadUrl operation middleware
func (siw *ServerInterfaceWrapper) PostAssetsV1UploadUrl(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, GoogleCookieAuthScopes, []string{"admin"})

	ctx = context.WithValue(ctx, GoogleBearerAuthScopes, []string{"admin"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAssetsV1UploadUrl(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/assets/v1", wrapper.GetAssetsV1)
	m.HandleFunc("DELETE "+options.BaseURL+"/assets/v1/by-path", wrapper.DeleteAssetsV1ByPath)
	m.HandleFunc("GET "+options.BaseURL+"/assets/v1/by-path", wrapper.GetAssetsV1ByPath)
	m.HandleFunc("POST "+options.BaseURL+"/assets/v1/by-path/confirm", wrapper.PostAssetsV1ByPathConfirm)
	m.HandleFunc("POST "+options.BaseURL+"/assets/v1/folders", wrapper.PostAssetsV1Folders)
	m.HandleFunc("POST "+options.BaseURL+"/assets/v1/upload-url", wrapper.PostAssetsV1UploadUrl)

	return m
}

type GetAssetsV1RequestObject struct {
	Params GetAssetsV1Params
}

type GetAssetsV1ResponseObject interface {
	VisitGetAssetsV1Response(w http.ResponseWriter) error
}

type GetAssetsV1200JSONResponse struct {
	Cursor      *string                                `json:"cursor,omitempty"`
	Data        []GetAssetsV1200JSONResponse_Data_Item `json:"data"`
	HasNextPage bool                                   `json:"hasNextPage"`
}

func (response GetAssetsV1200JSONResponse) VisitGetAssetsV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAssetsV1400JSONResponse Error

func (response GetAssetsV1400JSONResponse) VisitGetAssetsV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetAssetsV1500JSONResponse Error

func (response GetAssetsV1500JSONResponse) VisitGetAssetsV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAssetsV1ByPathRequestObject struct {
	Params DeleteAssetsV1ByPathParams
}

type DeleteAssetsV1ByPathResponseObject interface {
	VisitDeleteAssetsV1ByPathResponse(w http.ResponseWriter) error
}

type DeleteAssetsV1ByPath204Response struct {
}

func (response DeleteAssetsV1ByPath204Response) VisitDeleteAssetsV1ByPathResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteAssetsV1ByPath400JSONResponse Error

func (response DeleteAssetsV1ByPath400JSONResponse) VisitDeleteAssetsV1ByPathResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAssetsV1ByPath401JSONResponse Error

func (response DeleteAssetsV1ByPath401JSONResponse) VisitDeleteAssetsV1ByPathResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAssetsV1ByPath404JSONResponse Error

func (response DeleteAssetsV1ByPath404JSONResponse) VisitDeleteAssetsV1ByPathResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAssetsV1ByPath500JSONResponse Error

func (response DeleteAssetsV1ByPath500JSONResponse) VisitDeleteAssetsV1ByPathResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetAssetsV1ByPathRequestObject struct {
	Params GetAssetsV1ByPathParams
}

type GetAssetsV1ByPathResponseObject interface {
	VisitGetAssetsV1ByPathResponse(w http.ResponseWriter) error
}

type GetAssetsV1ByPath200JSONResponse struct {
	Asset GetAssetsV1ByPath200JSONResponse_Asset `json:"asset"`
}

func (response GetAssetsV1ByPath200JSONResponse) VisitGetAssetsV1ByPathResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAssetsV1ByPath400JSONResponse Error

func (response GetAssetsV1ByPath400JSONResponse) VisitGetAssetsV1ByPathResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetAssetsV1ByPath404JSONResponse Error

func (response GetAssetsV1ByPath404JSONResponse) VisitGetAssetsV1ByPathResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetAssetsV1ByPath500JSONResponse Error

func (response GetAssetsV1ByPath500JSONResponse) VisitGetAssetsV1ByPathResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1ByPathConfirmRequestObject struct {
	Params PostAssetsV1ByPathConfirmParams
}

type PostAssetsV1ByPathConfirmResponseObject interface {
	VisitPostAssetsV1ByPathConfirmResponse(w http.ResponseWriter) error
}

type PostAssetsV1ByPathConfirm200JSONResponse struct {
	File AdminFile `json:"file"`
}

func (response PostAssetsV1ByPathConfirm200JSONResponse) VisitPostAssetsV1ByPathConfirmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1ByPathConfirm400JSONResponse Error

func (response PostAssetsV1ByPathConfirm400JSONResponse) VisitPostAssetsV1ByPathConfirmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1ByPathConfirm401JSONResponse Error

func (response PostAssetsV1ByPathConfirm401JSONResponse) VisitPostAssetsV1ByPathConfirmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1ByPathConfirm404JSONResponse Error

func (response PostAssetsV1ByPathConfirm404JSONResponse) VisitPostAssetsV1ByPathConfirmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1ByPathConfirm409JSONResponse Error

func (response PostAssetsV1ByPathConfirm409JSONResponse) VisitPostAssetsV1ByPathConfirmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1ByPathConfirm500JSONResponse Error

func (response PostAssetsV1ByPathConfirm500JSONResponse) VisitPostAssetsV1ByPathConfirmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1FoldersRequestObject struct {
	Body *PostAssetsV1FoldersJSONRequestBody
}

type PostAssetsV1FoldersResponseObject interface {
	VisitPostAssetsV1FoldersResponse(w http.ResponseWriter) error
}

type PostAssetsV1Folders201JSONResponse struct {
	Folder AdminFolder `json:"folder"`
}

func (response PostAssetsV1Folders201JSONResponse) VisitPostAssetsV1FoldersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1Folders400JSONResponse Error

func (response PostAssetsV1Folders400JSONResponse) VisitPostAssetsV1FoldersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1Folders401JSONResponse Error

func (response PostAssetsV1Folders401JSONResponse) VisitPostAssetsV1FoldersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1Folders404JSONResponse Error

func (response PostAssetsV1Folders404JSONResponse) VisitPostAssetsV1FoldersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1Folders409JSONResponse Error

func (response PostAssetsV1Folders409JSONResponse) VisitPostAssetsV1FoldersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1Folders500JSONResponse Error

func (response PostAssetsV1Folders500JSONResponse) VisitPostAssetsV1FoldersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1UploadUrlRequestObject struct {
	Body *PostAssetsV1UploadUrlJSONRequestBody
}

type PostAssetsV1UploadUrlResponseObject interface {
	VisitPostAssetsV1UploadUrlResponse(w http.ResponseWriter) error
}

type PostAssetsV1UploadUrl200JSONResponse UploadResponse

func (response PostAssetsV1UploadUrl200JSONResponse) VisitPostAssetsV1UploadUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1UploadUrl400JSONResponse Error

func (response PostAssetsV1UploadUrl400JSONResponse) VisitPostAssetsV1UploadUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1UploadUrl401JSONResponse Error

func (response PostAssetsV1UploadUrl401JSONResponse) VisitPostAssetsV1UploadUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1UploadUrl404JSONResponse Error

func (response PostAssetsV1UploadUrl404JSONResponse) VisitPostAssetsV1UploadUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1UploadUrl500JSONResponse Error

func (response PostAssetsV1UploadUrl500JSONResponse) VisitPostAssetsV1UploadUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get all assets at a path
	// (GET /assets/v1)
	GetAssetsV1(ctx context.Context, request GetAssetsV1RequestObject) (GetAssetsV1ResponseObject, error)
	// Delete an asset
	// (DELETE /assets/v1/by-path)
	DeleteAssetsV1ByPath(ctx context.Context, request DeleteAssetsV1ByPathRequestObject) (DeleteAssetsV1ByPathResponseObject, error)
	// Get an asset
	// (GET /assets/v1/by-path)
	GetAssetsV1ByPath(ctx context.Context, request GetAssetsV1ByPathRequestObject) (GetAssetsV1ByPathResponseObject, error)
	// Confirm file upload
	// (POST /assets/v1/by-path/confirm)
	PostAssetsV1ByPathConfirm(ctx context.Context, request PostAssetsV1ByPathConfirmRequestObject) (PostAssetsV1ByPathConfirmResponseObject, error)
	// Create a folder
	// (POST /assets/v1/folders)
	PostAssetsV1Folders(ctx context.Context, request PostAssetsV1FoldersRequestObject) (PostAssetsV1FoldersResponseObject, error)
	// Get a presigned upload URL
	// (POST /assets/v1/upload-url)
	PostAssetsV1UploadUrl(ctx context.Context, request PostAssetsV1UploadUrlRequestObject) (PostAssetsV1UploadUrlResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetAssetsV1 operation middleware
func (sh *strictHandler) GetAssetsV1(w http.ResponseWriter, r *http.Request, params GetAssetsV1Params) {
	var request GetAssetsV1RequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAssetsV1(ctx, request.(GetAssetsV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAssetsV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAssetsV1ResponseObject); ok {
		if err := validResponse.VisitGetAssetsV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteAssetsV1ByPath operation middleware
func (sh *strictHandler) DeleteAssetsV1ByPath(w http.ResponseWriter, r *http.Request, params DeleteAssetsV1ByPathParams) {
	var request DeleteAssetsV1ByPathRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteAssetsV1ByPath(ctx, request.(DeleteAssetsV1ByPathRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteAssetsV1ByPath")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteAssetsV1ByPathResponseObject); ok {
		if err := validResponse.VisitDeleteAssetsV1ByPathResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAssetsV1ByPath operation middleware
func (sh *strictHandler) GetAssetsV1ByPath(w http.ResponseWriter, r *http.Request, params GetAssetsV1ByPathParams) {
	var request GetAssetsV1ByPathRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAssetsV1ByPath(ctx, request.(GetAssetsV1ByPathRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAssetsV1ByPath")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAssetsV1ByPathResponseObject); ok {
		if err := validResponse.VisitGetAssetsV1ByPathResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAssetsV1ByPathConfirm operation middleware
func (sh *strictHandler) PostAssetsV1ByPathConfirm(w http.ResponseWriter, r *http.Request, params PostAssetsV1ByPathConfirmParams) {
	var request PostAssetsV1ByPathConfirmRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAssetsV1ByPathConfirm(ctx, request.(PostAssetsV1ByPathConfirmRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAssetsV1ByPathConfirm")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAssetsV1ByPathConfirmResponseObject); ok {
		if err := validResponse.VisitPostAssetsV1ByPathConfirmResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAssetsV1Folders operation middleware
func (sh *strictHandler) PostAssetsV1Folders(w http.ResponseWriter, r *http.Request) {
	var request PostAssetsV1FoldersRequestObject

	var body PostAssetsV1FoldersJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAssetsV1Folders(ctx, request.(PostAssetsV1FoldersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAssetsV1Folders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAssetsV1FoldersResponseObject); ok {
		if err := validResponse.VisitPostAssetsV1FoldersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAssetsV1UploadUrl operation middleware
func (sh *strictHandler) PostAssetsV1UploadUrl(w http.ResponseWriter, r *http.Request) {
	var request PostAssetsV1UploadUrlRequestObject

	var body PostAssetsV1UploadUrlJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAssetsV1UploadUrl(ctx, request.(PostAssetsV1UploadUrlRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAssetsV1UploadUrl")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAssetsV1UploadUrlResponseObject); ok {
		if err := validResponse.VisitPostAssetsV1UploadUrlResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xai2/bNhP/Vwh+H7Cm8Dtx1xgY8DlOnDpzHst7aYOBls42W4nUSCqOUuR//8CHZMlW",
	"EmdNu65YgWyWRPGOd8ff/e7Ez9jjYcQZMCVx5zOW3hRCYn52/ZCyrpSg9JVPpSdoSBlRXOgbIYkiyib6",
	"55gGgDv4P/X5XHU3Ud3M0tcDKnjMAx/E4yPtkPsKjgSPQKjkgIR6cpVEoG9zBodj3Hn/Gf9XwPhpqfeV",
	"VUY6qdf3FTx/tfMZkyBYQdpRPAqol4lzmlMwZvQEEAV+11gRbkkYGWO1Gq12tfG22tw8bb7tbLzptNdr",
	"zbftK2MmERKFO9gnCqqKhtp2Aoh/yIIEd5SIoWLt0cFSCe2E+0oqZysx3gLtrUhRznAH74SEBoiPkZoC",
	"Inp9aDblKI4CTnzwze2xddFcQTPuf9QjpDbjIvBX0YH6xUU23L9qyX/Sf/kFxzFdSY5URMXGuo+5RTvk",
	"xI68v9ez/hlTAT7uvMdGjJulknNR3ozXmWA++gieyoeHC+RnBkga2/+cEHFv2Aix6v8zYqTM389ys8a9",
	"U3P/MwYWh3qWcQHGrvOWcI+WVtszcqznj+HPGKRxctH/BVcseubQ/CAByt1OHVXikkFIJiDRmAszYspD",
	"iMgEkEcEjyUEuIJDcjsENlFT3Gk2Go0SrZnB3EVNNBIXJSOVhkhBh3JZrXa7gkPKMtklgiOinywKPiIC",
	"mEpl6jHoVSwBfcD1D9gsVXCu1go61KkxBH4qMoxEt+LlUKjgHSFsvlvYstyHp/DHvNrTA+8rOAQpyQSK",
	"sd9lKGZwG4GnNxno8Yh7XiwE+LUnVTc6zGd+UPue0zUN4wFTIBgJ7NIqeEhDqg5jdTje4jHztc0G7IYE",
	"1O/FQpohB1z19TNcwTthpJIt7ifzYe6qG+hNmezcUqnsJFGszvUAoh2ZiuvGapr91tvsgKszl4pwBWvU",
	"PuV8SMREr85unQOujFxcccGQ3U7VOuCq62jGOQhJOetxNg6op3KGmQdaLjfkLBMB8/WACvY4G1MRgl/c",
	"5vPbJXNalP9ixpRjE09RpoW88mWcaYHFrJ7PrrO1p7Rpca8wBWyOppk1zRatR8bgRVAqse4CSM5n2SeU",
	"oSkIjkaEMRAvhH1zAXruqp27tqTsS6JaGYDVc8ov8yB6V4LT2gtIP0KUoVGiDApmEzcbG2/bP7/JZVTK",
	"1JuN+fSUKZjYeFLOZY8S6CxT3ldwLIJlfXrbB+jseJj5ZYlqTpWKZKdeJ3oqWZvziToZec3W+pNIaJ5W",
	"ClheKYSdM5VVsAwoCxH9UAT3eMxUSV6MwxEInRmpglCiV3qBEhHmO+fKNeRTAZ4KEu0SNaWyJHW3yzzw",
	"YNS/aJ7/lql7tSz97Nh7RkRYN5ZFgU1DD/K0BSArrnR/sL+D9IwZRVoM8y+Bu2dwwkWxL4yPev6DUn54",
	"KOiEaq30EORs/jfAKJpNQUBmDDSjQYBGgKTiwmTu54BsOV3MjFCEmcdiSkacyZLsCLcRFSC7JcByMQVm",
	"lhEJkHTCwDc46t4oLCRfK26uUCuWunXgL+sw2M4HluXdBsA09bdsyDy1zYQiB/+Lpd2yblyEfQqBbwxG",
	"fJ/a8D8qGPLxLYT7XIRobGZBakoUCmOpdFhQ5gWxD76FZkBhHCgaEaHqWm7VJ4qgo8OTUyQsLtTQaWoN",
	"qiQE42wm4utpAiIVmlE1dVaDwDebAf2k3/mpljfRZ9yz4VM9ddCfw4gjHlAvwR0MyV4A77YiL+w3yMVm",
	"PPjI6f7HbnLQa8z2Txq3h+e/3e7f8dn+Np/t9zkd9vY+jlrtT+TyOBq12neDj9EIkj3qXxyIq8vf6CHd",
	"i35v9afDi/6d1zpveMne5rAv6dXlDh32Bp9I67w9oDO6v92duT9l/q/lbXdnw9PcvdzfIGjIi2Qv8E4G",
	"ckCPt0etduPqot0Ynh+3vd0zrVc0uuizq5PN2Sj06OXJ7WgQHtyM2HEwYr+p0e55fLV+zIeXe9NR6AcD",
	"Orsdbg9a+x93Ggfb3dnleXMTV/BltRveVbvBhAuqpqGuoy5ONqrv9ru96sm7bqv9JhvUE+ADU5QEetSv",
	"g+7g8KR/uH1w8PPOZXf/aLhTbzVaG41mc7MeyyoQqarNulyvk5nc+MP5O5tsW9e5ZquZN06bLR3AV9nz",
	"EzphRMXCdEZGng/jZmt9o/3m57ebjede4wr+BMmqe+i+BHfshjwrI2RHGZyYuNaYotJ24HyrK15K0jQ7",
	"qzqmJtdrJCR3nJGZrHk8rD+Jnw5m8uoV9nclh4fLaKopL3ixoCo50RTAbvwJ55MAtoAIELq41PdG5qqf",
	"IsvexanmgOYd3HFP58rqtWmb2Zl6nH+ikM5Eman79K2USXTw7uHh7nDnj+7Z6bs/7NxuJhLRXyHB91pV",
	"ysZ82fhdhrpHA5OEQ8LIhLIJsuYsJY5psh70ul00g5GkCkxrgCrLA/X9rn2/ezTAFXxjy1/cwc1ao2aC",
	"g0fASERxB6+bWzaXGuM50l2/aRpTQkkaOgYlKNxozVBApdIJgQTBY1oTZZSWEXh0TME3ebn2gX1gr19r",
	"w+o96ZmuQOf16w+sikxbFcUShESvDHjaJqT0eARrSIAH9AbQOE7lIh8UoYFEr+bfKSz9Mm9Tv4KyHl/2",
	"s6sqyHZ917RQS/rzUnmsygUHNKQK/EXZuZJ/LlxPIoFJqvSbISiic8jaB4aNJ4RZt861eBeUdd150/hE",
	"kBAUCGlq9UWaoxMKtw5wlh8LHj7UCTNh+2cMIplHrSMv8/1oW6eWTRfrgNKdvFTYmfaQERvpQDYLe0C2",
	"l7aSyqT93tqMr9b3pv67fTl4F9z4J1vhaP08vuptNcju2eTqon/n754ng91zdjX75ZdVlNsnt4hllZmz",
	"mOJoDMqbPqCk8XJBRx/GJA4U7rQaOTDUFyG5pWEcOv4eUuaulqu4+2ttc8v/zJ5rNRq5csJwmigK3Iao",
	"f5SW8s+VWKhCrCVf2IAVTQ+NNFPE6h/P+NRmm16rtY3c2Ot50iJCkESrMCXyAG7V0WKjtNDiH3EeAGFL",
	"qcXoX5yjJIMs8cLuHNNsUkPHoGLBJMoBiw5xMsctDQRzwKqgPAzooVxNQciaXtLGM339ZEO5bA1bxM/Y",
	"qRba/hZCz9gnxmcMSRA3IGz3ulbI0bjz/rqCZRyGRCQW7vKJgyhEbEtAvzRPRPVRUp3XegGoklpz29xH",
	"hDlEHiU2N5g847IJZ0FSQ2akSbJpjWjqwTGhAaJjRBWSSt/QxiKU6USWIJvSuEAyHrmkVltCb6tDCuBb",
	"yZGF10dhvJ8qqaHIfGsz6r+C2qRW0TA+5rw+IqKmbtUH/BJA7ipcXX27snsROpfhaaOEtrjEp5fsIxl7",
	"HkipTZ78LWGeWsy5lHGFIIxUsua0aX6L+NeIwAW9A99J3fj6Uq0f9HrHPGb+d7bdP5dQ6Pf2MzG+1ulh",
	"mavPHxewYmGDG3ZeRk41pnCW7SNTuRhOouNirYgL//LPh/nn14Av7YiXZ6Z/BdC+hG+R9IPe1+ZDC3zG",
	"yl2FwpymjvgRuMu/KFpCmjIULCVKddeINbHLZQlK9uwA1/kktsEzJRKNAFjuIBhHJ+sF+rQEGUdcLmCG",
	"m/vZ0GH7yd8X8fkSnBi7j98rnkssaYyttNnN193sHMJ3xMTMRx+u5tGUgKroFGBzBJXmqY29H56m9VNr",
	"zPFlo7H59eW6sy8mQALqpYxoRiQKuW97caMEEWZgPvXh2g9LIx042ei0kbkIoq6+ewQ8DXmTiCAGs7Ti",
	"KO9wrgydfSfUggBIZc5QvZT1y04dlgWpXYohpzpoHK1cAtj7JZxsfglOZocsVj6XvYiV2QHMp9Eyt8Tv",
	"AS1/dNwrfo3/GwDQOZzYs4gIzGHEHxfeTFxnra1FaLOAV3WnssrRLa0YyMIpA10L2Pdd80wjaHaMaZkp",
	"mq/iUcH95ru48cDjYHiW+xb4NeCweKynzGv202fKaFbHwcaL6+iOiZRtrcw97kut9hJhaU9gsP0voH1j",
	"QPsREcWUmzkomMeaVe4poQ9Js2LMGko/bwrux55hIXaQO6uZOxwa0fzJULz8xW/IPXMk7qZsik69Hujn",
	"Uy5VZ73RaNTx/fX9/wMAAP//FjB/4P82AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
