//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	GoogleBearerAuthScopes = "googleBearerAuth.Scopes"
	GoogleCookieAuthScopes = "googleCookieAuth.Scopes"
)

// Defines values for AssetType.
const (
	File   AssetType = "file"
	Folder AssetType = "folder"
)

// Defines values for ErrorCode.
const (
	AlreadyExists        ErrorCode = "AlreadyExists"
	AssetNotUploaded     ErrorCode = "AssetNotUploaded"
	AuthError            ErrorCode = "AuthError"
	EmptyBody            ErrorCode = "EmptyBody"
	FileNotConfirmed     ErrorCode = "FileNotConfirmed"
	FileTooLarge         ErrorCode = "FileTooLarge"
	FolderNotEmpty       ErrorCode = "FolderNotEmpty"
	InputValidationError ErrorCode = "InputValidationError"
	InternalError        ErrorCode = "InternalError"
	InvalidBody          ErrorCode = "InvalidBody"
	InvalidCursor        ErrorCode = "InvalidCursor"
	LimitOutOfBounds     ErrorCode = "LimitOutOfBounds"
	NotAFile             ErrorCode = "NotAFile"
	NotFound             ErrorCode = "NotFound"
	ParentFolderNotFound ErrorCode = "ParentFolderNotFound"
	VersionConflict      ErrorCode = "VersionConflict"
)

// Defines values for FileStatus.
const (
	Confirmed FileStatus = "confirmed"
	Pending   FileStatus = "pending"
)

// AdminAsset defines model for AdminAsset.
type AdminAsset struct {
	union json.RawMessage
}

// AdminFile defines model for AdminFile.
type AdminFile struct {
	ContentType string     `json:"contentType"`
	CreatedAt   *time.Time `json:"createdAt,omitempty"`

	// CreatedBy Email of the admin who uploaded the file
	CreatedBy   *string             `json:"createdBy,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	Name        string              `json:"name"`

	// Path Parent folder path
	Path string `json:"path"`

	// Size File size in bytes
	Size   int64      `json:"size"`
	Status FileStatus `json:"status"`
	Type   AssetType  `json:"type"`

	// Url CDN URL for the file
	Url     string `json:"url"`
	Version *int   `json:"version,omitempty"`
}

// AdminFolder defines model for AdminFolder.
type AdminFolder struct {
	// ContentCount Number of items (files and folders) directly in this folder
	ContentCount int        `json:"contentCount"`
	CreatedAt    *time.Time `json:"createdAt,omitempty"`

	// CreatedBy Email of the admin who created the folder
	CreatedBy   *string             `json:"createdBy,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	Name        string              `json:"name"`

	// Path Parent folder path
	Path    string    `json:"path"`
	Type    AssetType `json:"type"`
	Version *int      `json:"version,omitempty"`
}

// Asset defines model for Asset.
type Asset struct {
	union json.RawMessage
}

// AssetType defines model for AssetType.
type AssetType string

// CreateFolderRequest defines model for CreateFolderRequest.
type CreateFolderRequest struct {
	// Description Optional description of the folder
	Description *string `json:"description,omitempty"`

	// Name Name of the folder to create
	Name string `json:"name"`

	// Path Parent folder path (use "/" for root)
	Path string `json:"path"`
}

// Error defines model for Error.
type Error struct {
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// FileStatus defines model for FileStatus.
type FileStatus string

// PublicAsset defines model for PublicAsset.
type PublicAsset struct {
	union json.RawMessage
}

// PublicFile defines model for PublicFile.
type PublicFile struct {
	ContentType string  `json:"contentType"`
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`

	// Path Parent folder path
	Path string `json:"path"`

	// Size File size in bytes
	Size int64     `json:"size"`
	Type AssetType `json:"type"`

	// Url CDN URL for the file
	Url string `json:"url"`
}

// PublicFolder defines model for PublicFolder.
type PublicFolder struct {
	// ContentCount Number of items (files and folders) directly in this folder
	ContentCount int     `json:"contentCount"`
	Description  *string `json:"description,omitempty"`
	Name         string  `json:"name"`

	// Path Parent folder path
	Path string    `json:"path"`
	Type AssetType `json:"type"`
}

// UploadRequest defines model for UploadRequest.
type UploadRequest struct {
	// ContentType MIME type of the file
	ContentType string `json:"contentType"`

	// Description Optional description of the file
	Description *string `json:"description,omitempty"`

	// FileName Original file name
	FileName string `json:"fileName"`

	// Path Parent folder path where the file will be stored
	Path string `json:"path"`
}

// UploadResponse defines model for UploadResponse.
type UploadResponse struct {
	// ExpiresAt When the presigned URL expires
	ExpiresAt time.Time `json:"expiresAt"`

	// FileId ID of the file (use this to confirm the upload)
	FileId openapi_types.UUID `json:"fileId"`

	// FormFields Form fields that must be included in the multipart/form-data POST request. The file itself must be added last with the field name 'file'.
	FormFields map[string]string `json:"formFields"`

	// UploadUrl Presigned POST URL to upload the file to
	UploadUrl string `json:"uploadUrl"`
}

// GetAssetsV1Params defines parameters for GetAssetsV1.
type GetAssetsV1Params struct {
	// Path Path to list assets from (use "/" for root)
	Path string `form:"path" json:"path"`

	// Cursor Cursor for pagination
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Max number of assets to fetch
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// DeleteAssetsV1ByPathParams defines parameters for DeleteAssetsV1ByPath.
type DeleteAssetsV1ByPathParams struct {
	// Path Full path to the asset (e.g., "/foo/bar.txt")
	Path string `form:"path" json:"path"`
}

// GetAssetsV1ByPathParams defines parameters for GetAssetsV1ByPath.
type GetAssetsV1ByPathParams struct {
	// Path Full path to the asset (e.g., "/foo/bar.txt" or "/" for root)
	Path string `form:"path" json:"path"`
}

// PostAssetsV1ByPathConfirmParams defines parameters for PostAssetsV1ByPathConfirm.
type PostAssetsV1ByPathConfirmParams struct {
	// Path Full path to the file (e.g., "/foo/bar.txt")
	Path string `form:"path" json:"path"`
}

// PostAssetsV1ByPathReplaceUrlParams defines parameters for PostAssetsV1ByPathReplaceUrl.
type PostAssetsV1ByPathReplaceUrlParams struct {
	// Path Full path to the file to replace (e.g., "/foo/bar.txt")
	Path string `form:"path" json:"path"`
}

// PostAssetsV1FoldersJSONRequestBody defines body for PostAssetsV1Folders for application/json ContentType.
type PostAssetsV1FoldersJSONRequestBody = CreateFolderRequest

// PostAssetsV1UploadUrlJSONRequestBody defines body for PostAssetsV1UploadUrl for application/json ContentType.
type PostAssetsV1UploadUrlJSONRequestBody = UploadRequest

// AsAdminFile returns the union data inside the AdminAsset as a AdminFile
func (t AdminAsset) AsAdminFile() (AdminFile, error) {
	var body AdminFile
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAdminFile overwrites any union data inside the AdminAsset as the provided AdminFile
func (t *AdminAsset) FromAdminFile(v AdminFile) error {
	v.Type = "file"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAdminFile performs a merge with any union data inside the AdminAsset, using the provided AdminFile
func (t *AdminAsset) MergeAdminFile(v AdminFile) error {
	v.Type = "file"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAdminFolder returns the union data inside the AdminAsset as a AdminFolder
func (t AdminAsset) AsAdminFolder() (AdminFolder, error) {
	var body AdminFolder
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAdminFolder overwrites any union data inside the AdminAsset as the provided AdminFolder
func (t *AdminAsset) FromAdminFolder(v AdminFolder) error {
	v.Type = "folder"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAdminFolder performs a merge with any union data inside the AdminAsset, using the provided AdminFolder
func (t *AdminAsset) MergeAdminFolder(v AdminFolder) error {
	v.Type = "folder"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AdminAsset) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t AdminAsset) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "file":
		return t.AsAdminFile()
	case "folder":
		return t.AsAdminFolder()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t AdminAsset) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AdminAsset) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsAdminAsset returns the union data inside the Asset as a AdminAsset
func (t Asset) AsAdminAsset() (AdminAsset, error) {
	var body AdminAsset
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAdminAsset overwrites any union data inside the Asset as the provided AdminAsset
func (t *Asset) FromAdminAsset(v AdminAsset) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAdminAsset performs a merge with any union data inside the Asset, using the provided AdminAsset
func (t *Asset) MergeAdminAsset(v AdminAsset) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPublicAsset returns the union data inside the Asset as a PublicAsset
func (t Asset) AsPublicAsset() (PublicAsset, error) {
	var body PublicAsset
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPublicAsset overwrites any union data inside the Asset as the provided PublicAsset
func (t *Asset) FromPublicAsset(v PublicAsset) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePublicAsset performs a merge with any union data inside the Asset, using the provided PublicAsset
func (t *Asset) MergePublicAsset(v PublicAsset) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Asset) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Asset) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsPublicFile returns the union data inside the PublicAsset as a PublicFile
func (t PublicAsset) AsPublicFile() (PublicFile, error) {
	var body PublicFile
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPublicFile overwrites any union data inside the PublicAsset as the provided PublicFile
func (t *PublicAsset) FromPublicFile(v PublicFile) error {
	v.Type = "file"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePublicFile performs a merge with any union data inside the PublicAsset, using the provided PublicFile
func (t *PublicAsset) MergePublicFile(v PublicFile) error {
	v.Type = "file"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPublicFolder returns the union data inside the PublicAsset as a PublicFolder
func (t PublicAsset) AsPublicFolder() (PublicFolder, error) {
	var body PublicFolder
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPublicFolder overwrites any union data inside the PublicAsset as the provided PublicFolder
func (t *PublicAsset) FromPublicFolder(v PublicFolder) error {
	v.Type = "folder"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePublicFolder performs a merge with any union data inside the PublicAsset, using the provided PublicFolder
func (t *PublicAsset) MergePublicFolder(v PublicFolder) error {
	v.Type = "folder"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PublicAsset) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t PublicAsset) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "file":
		return t.AsPublicFile()
	case "folder":
		return t.AsPublicFolder()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t PublicAsset) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PublicAsset) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all assets at a path
	// (GET /assets/v1)
	GetAssetsV1(w http.ResponseWriter, r *http.Request, params GetAssetsV1Params)
	// Delete an asset
	// (DELETE /assets/v1/by-path)
	DeleteAssetsV1ByPath(w http.ResponseWriter, r *http.Request, params DeleteAssetsV1ByPathParams)
	// Get an asset
	// (GET /assets/v1/by-path)
	GetAssetsV1ByPath(w http.ResponseWriter, r *http.Request, params GetAssetsV1ByPathParams)
	// Confirm file upload
	// (POST /assets/v1/by-path/confirm)
	PostAssetsV1ByPathConfirm(w http.ResponseWriter, r *http.Request, params PostAssetsV1ByPathConfirmParams)
	// Get a presigned URL to replace a file's contents
	// (POST /assets/v1/by-path/replace-url)
	PostAssetsV1ByPathReplaceUrl(w http.ResponseWriter, r *http.Request, params PostAssetsV1ByPathReplaceUrlParams)
	// Create a folder
	// (POST /assets/v1/folders)
	PostAssetsV1Folders(w http.ResponseWriter, r *http.Request)
	// Get a presigned upload URL
	// (POST /assets/v1/upload-url)
	PostAssetsV1UploadUrl(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAssetsV1 operation middleware
func (siw *ServerInterfaceWrapper) GetAssetsV1(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, GoogleCookieAuthScopes, []string{})

	ctx = context.WithValue(ctx, GoogleBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAssetsV1Params

	// ------------- Required query parameter "path" -------------

	if paramValue := r.URL.Query().Get("path"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", r.URL.Query(), &params.Cursor)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAssetsV1(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAssetsV1ByPath operation middleware
func (siw *ServerInterfaceWrapper) DeleteAssetsV1ByPath(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, GoogleCookieAuthScopes, []string{"admin"})

	ctx = context.WithValue(ctx, GoogleBearerAuthScopes, []string{"admin"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteAssetsV1ByPathParams

	// ------------- Required query parameter "path" -------------

	if paramValue := r.URL.Query().Get("path"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAssetsV1ByPath(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAssetsV1ByPath operation middleware
func (siw *ServerInterfaceWrapper) GetAssetsV1ByPath(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, GoogleCookieAuthScopes, []string{})

	ctx = context.WithValue(ctx, GoogleBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAssetsV1ByPathParams

	// ------------- Required query parameter "path" -------------

	if paramValue := r.URL.Query().Get("path"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAssetsV1ByPath(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAssetsV1ByPathConfirm operation middleware
func (siw *ServerInterfaceWrapper) PostAssetsV1ByPathConfirm(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, GoogleCookieAuthScopes, []string{"admin"})

	ctx = context.WithValue(ctx, GoogleBearerAuthScopes, []string{"admin"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params PostAssetsV1ByPathConfirmParams

	// ------------- Required query parameter "path" -------------

	if paramValue := r.URL.Query().Get("path"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAssetsV1ByPathConfirm(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAssetsV1ByPathReplaceUrl operation middleware
func (siw *ServerInterfaceWrapper) PostAssetsV1ByPathReplaceUrl(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, GoogleCookieAuthScopes, []string{"admin"})

	ctx = context.WithValue(ctx, GoogleBearerAuthScopes, []string{"admin"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params PostAssetsV1ByPathReplaceUrlParams

	// ------------- Required query parameter "path" -------------

	if paramValue := r.URL.Query().Get("path"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAssetsV1ByPathReplaceUrl(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAssetsV1Folders operation middleware
func (siw *ServerInterfaceWrapper) PostAssetsV1Folders(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, GoogleCookieAuthScopes, []string{"admin"})

	ctx = context.WithValue(ctx, GoogleBearerAuthScopes, []string{"admin"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAssetsV1Folders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAssetsV1UploadUrl operation middleware
func (siw *ServerInterfaceWrapper) PostAssetsV1UploadUrl(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, GoogleCookieAuthScopes, []string{"admin"})

	ctx = context.WithValue(ctx, GoogleBearerAuthScopes, []string{"admin"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAssetsV1UploadUrl(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/assets/v1", wrapper.GetAssetsV1)
	m.HandleFunc("DELETE "+options.BaseURL+"/assets/v1/by-path", wrapper.DeleteAssetsV1ByPath)
	m.HandleFunc("GET "+options.BaseURL+"/assets/v1/by-path", wrapper.GetAssetsV1ByPath)
	m.HandleFunc("POST "+options.BaseURL+"/assets/v1/by-path/confirm", wrapper.PostAssetsV1ByPathConfirm)
	m.HandleFunc("POST "+options.BaseURL+"/assets/v1/by-path/replace-url", wrapper.PostAssetsV1ByPathReplaceUrl)
	m.HandleFunc("POST "+options.BaseURL+"/assets/v1/folders", wrapper.PostAssetsV1Folders)
	m.HandleFunc("POST "+options.BaseURL+"/assets/v1/upload-url", wrapper.PostAssetsV1UploadUrl)

	return m
}

type GetAssetsV1RequestObject struct {
	Params GetAssetsV1Params
}

type GetAssetsV1ResponseObject interface {
	VisitGetAssetsV1Response(w http.ResponseWriter) error
}

type GetAssetsV1200JSONResponse struct {
	// ContentCount Total number of items in the folder
	ContentCount int     `json:"contentCount"`
	Cursor       *string `json:"cursor,omitempty"`
	Data         []Asset `json:"data"`
	HasNextPage  bool    `json:"hasNextPage"`
}

func (response GetAssetsV1200JSONResponse) VisitGetAssetsV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAssetsV1400JSONResponse Error

func (response GetAssetsV1400JSONResponse) VisitGetAssetsV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetAssetsV1500JSONResponse Error

func (response GetAssetsV1500JSONResponse) VisitGetAssetsV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAssetsV1ByPathRequestObject struct {
	Params DeleteAssetsV1ByPathParams
}

type DeleteAssetsV1ByPathResponseObject interface {
	VisitDeleteAssetsV1ByPathResponse(w http.ResponseWriter) error
}

type DeleteAssetsV1ByPath204Response struct {
}

func (response DeleteAssetsV1ByPath204Response) VisitDeleteAssetsV1ByPathResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteAssetsV1ByPath400JSONResponse Error

func (response DeleteAssetsV1ByPath400JSONResponse) VisitDeleteAssetsV1ByPathResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAssetsV1ByPath401JSONResponse Error

func (response DeleteAssetsV1ByPath401JSONResponse) VisitDeleteAssetsV1ByPathResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAssetsV1ByPath404JSONResponse Error

func (response DeleteAssetsV1ByPath404JSONResponse) VisitDeleteAssetsV1ByPathResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAssetsV1ByPath500JSONResponse Error

func (response DeleteAssetsV1ByPath500JSONResponse) VisitDeleteAssetsV1ByPathResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetAssetsV1ByPathRequestObject struct {
	Params GetAssetsV1ByPathParams
}

type GetAssetsV1ByPathResponseObject interface {
	VisitGetAssetsV1ByPathResponse(w http.ResponseWriter) error
}

type GetAssetsV1ByPath200JSONResponse struct {
	Asset Asset `json:"asset"`
}

func (response GetAssetsV1ByPath200JSONResponse) VisitGetAssetsV1ByPathResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAssetsV1ByPath400JSONResponse Error

func (response GetAssetsV1ByPath400JSONResponse) VisitGetAssetsV1ByPathResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetAssetsV1ByPath404JSONResponse Error

func (response GetAssetsV1ByPath404JSONResponse) VisitGetAssetsV1ByPathResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetAssetsV1ByPath500JSONResponse Error

func (response GetAssetsV1ByPath500JSONResponse) VisitGetAssetsV1ByPathResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1ByPathConfirmRequestObject struct {
	Params PostAssetsV1ByPathConfirmParams
}

type PostAssetsV1ByPathConfirmResponseObject interface {
	VisitPostAssetsV1ByPathConfirmResponse(w http.ResponseWriter) error
}

type PostAssetsV1ByPathConfirm200JSONResponse struct {
	File AdminFile `json:"file"`
}

func (response PostAssetsV1ByPathConfirm200JSONResponse) VisitPostAssetsV1ByPathConfirmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1ByPathConfirm400JSONResponse Error

func (response PostAssetsV1ByPathConfirm400JSONResponse) VisitPostAssetsV1ByPathConfirmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1ByPathConfirm401JSONResponse Error

func (response PostAssetsV1ByPathConfirm401JSONResponse) VisitPostAssetsV1ByPathConfirmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1ByPathConfirm404JSONResponse Error

func (response PostAssetsV1ByPathConfirm404JSONResponse) VisitPostAssetsV1ByPathConfirmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1ByPathConfirm409JSONResponse Error

func (response PostAssetsV1ByPathConfirm409JSONResponse) VisitPostAssetsV1ByPathConfirmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1ByPathConfirm500JSONResponse Error

func (response PostAssetsV1ByPathConfirm500JSONResponse) VisitPostAssetsV1ByPathConfirmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1ByPathReplaceUrlRequestObject struct {
	Params PostAssetsV1ByPathReplaceUrlParams
}

type PostAssetsV1ByPathReplaceUrlResponseObject interface {
	VisitPostAssetsV1ByPathReplaceUrlResponse(w http.ResponseWriter) error
}

type PostAssetsV1ByPathReplaceUrl200JSONResponse UploadResponse

func (response PostAssetsV1ByPathReplaceUrl200JSONResponse) VisitPostAssetsV1ByPathReplaceUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1ByPathReplaceUrl400JSONResponse Error

func (response PostAssetsV1ByPathReplaceUrl400JSONResponse) VisitPostAssetsV1ByPathReplaceUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1ByPathReplaceUrl401JSONResponse Error

func (response PostAssetsV1ByPathReplaceUrl401JSONResponse) VisitPostAssetsV1ByPathReplaceUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1ByPathReplaceUrl404JSONResponse Error

func (response PostAssetsV1ByPathReplaceUrl404JSONResponse) VisitPostAssetsV1ByPathReplaceUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1ByPathReplaceUrl500JSONResponse Error

func (response PostAssetsV1ByPathReplaceUrl500JSONResponse) VisitPostAssetsV1ByPathReplaceUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1FoldersRequestObject struct {
	Body *PostAssetsV1FoldersJSONRequestBody
}

type PostAssetsV1FoldersResponseObject interface {
	VisitPostAssetsV1FoldersResponse(w http.ResponseWriter) error
}

type PostAssetsV1Folders201JSONResponse struct {
	Folder AdminFolder `json:"folder"`
}

func (response PostAssetsV1Folders201JSONResponse) VisitPostAssetsV1FoldersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1Folders400JSONResponse Error

func (response PostAssetsV1Folders400JSONResponse) VisitPostAssetsV1FoldersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1Folders401JSONResponse Error

func (response PostAssetsV1Folders401JSONResponse) VisitPostAssetsV1FoldersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1Folders404JSONResponse Error

func (response PostAssetsV1Folders404JSONResponse) VisitPostAssetsV1FoldersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1Folders409JSONResponse Error

func (response PostAssetsV1Folders409JSONResponse) VisitPostAssetsV1FoldersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1Folders500JSONResponse Error

func (response PostAssetsV1Folders500JSONResponse) VisitPostAssetsV1FoldersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1UploadUrlRequestObject struct {
	Body *PostAssetsV1UploadUrlJSONRequestBody
}

type PostAssetsV1UploadUrlResponseObject interface {
	VisitPostAssetsV1UploadUrlResponse(w http.ResponseWriter) error
}

type PostAssetsV1UploadUrl200JSONResponse UploadResponse

func (response PostAssetsV1UploadUrl200JSONResponse) VisitPostAssetsV1UploadUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1UploadUrl400JSONResponse Error

func (response PostAssetsV1UploadUrl400JSONResponse) VisitPostAssetsV1UploadUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1UploadUrl401JSONResponse Error

func (response PostAssetsV1UploadUrl401JSONResponse) VisitPostAssetsV1UploadUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1UploadUrl404JSONResponse Error

func (response PostAssetsV1UploadUrl404JSONResponse) VisitPostAssetsV1UploadUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostAssetsV1UploadUrl500JSONResponse Error

func (response PostAssetsV1UploadUrl500JSONResponse) VisitPostAssetsV1UploadUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get all assets at a path
	// (GET /assets/v1)
	GetAssetsV1(ctx context.Context, request GetAssetsV1RequestObject) (GetAssetsV1ResponseObject, error)
	// Delete an asset
	// (DELETE /assets/v1/by-path)
	DeleteAssetsV1ByPath(ctx context.Context, request DeleteAssetsV1ByPathRequestObject) (DeleteAssetsV1ByPathResponseObject, error)
	// Get an asset
	// (GET /assets/v1/by-path)
	GetAssetsV1ByPath(ctx context.Context, request GetAssetsV1ByPathRequestObject) (GetAssetsV1ByPathResponseObject, error)
	// Confirm file upload
	// (POST /assets/v1/by-path/confirm)
	PostAssetsV1ByPathConfirm(ctx context.Context, request PostAssetsV1ByPathConfirmRequestObject) (PostAssetsV1ByPathConfirmResponseObject, error)
	// Get a presigned URL to replace a file's contents
	// (POST /assets/v1/by-path/replace-url)
	PostAssetsV1ByPathReplaceUrl(ctx context.Context, request PostAssetsV1ByPathReplaceUrlRequestObject) (PostAssetsV1ByPathReplaceUrlResponseObject, error)
	// Create a folder
	// (POST /assets/v1/folders)
	PostAssetsV1Folders(ctx context.Context, request PostAssetsV1FoldersRequestObject) (PostAssetsV1FoldersResponseObject, error)
	// Get a presigned upload URL
	// (POST /assets/v1/upload-url)
	PostAssetsV1UploadUrl(ctx context.Context, request PostAssetsV1UploadUrlRequestObject) (PostAssetsV1UploadUrlResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetAssetsV1 operation middleware
func (sh *strictHandler) GetAssetsV1(w http.ResponseWriter, r *http.Request, params GetAssetsV1Params) {
	var request GetAssetsV1RequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAssetsV1(ctx, request.(GetAssetsV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAssetsV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAssetsV1ResponseObject); ok {
		if err := validResponse.VisitGetAssetsV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteAssetsV1ByPath operation middleware
func (sh *strictHandler) DeleteAssetsV1ByPath(w http.ResponseWriter, r *http.Request, params DeleteAssetsV1ByPathParams) {
	var request DeleteAssetsV1ByPathRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteAssetsV1ByPath(ctx, request.(DeleteAssetsV1ByPathRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteAssetsV1ByPath")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteAssetsV1ByPathResponseObject); ok {
		if err := validResponse.VisitDeleteAssetsV1ByPathResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAssetsV1ByPath operation middleware
func (sh *strictHandler) GetAssetsV1ByPath(w http.ResponseWriter, r *http.Request, params GetAssetsV1ByPathParams) {
	var request GetAssetsV1ByPathRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAssetsV1ByPath(ctx, request.(GetAssetsV1ByPathRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAssetsV1ByPath")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAssetsV1ByPathResponseObject); ok {
		if err := validResponse.VisitGetAssetsV1ByPathResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAssetsV1ByPathConfirm operation middleware
func (sh *strictHandler) PostAssetsV1ByPathConfirm(w http.ResponseWriter, r *http.Request, params PostAssetsV1ByPathConfirmParams) {
	var request PostAssetsV1ByPathConfirmRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAssetsV1ByPathConfirm(ctx, request.(PostAssetsV1ByPathConfirmRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAssetsV1ByPathConfirm")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAssetsV1ByPathConfirmResponseObject); ok {
		if err := validResponse.VisitPostAssetsV1ByPathConfirmResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAssetsV1ByPathReplaceUrl operation middleware
func (sh *strictHandler) PostAssetsV1ByPathReplaceUrl(w http.ResponseWriter, r *http.Request, params PostAssetsV1ByPathReplaceUrlParams) {
	var request PostAssetsV1ByPathReplaceUrlRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAssetsV1ByPathReplaceUrl(ctx, request.(PostAssetsV1ByPathReplaceUrlRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAssetsV1ByPathReplaceUrl")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAssetsV1ByPathReplaceUrlResponseObject); ok {
		if err := validResponse.VisitPostAssetsV1ByPathReplaceUrlResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAssetsV1Folders operation middleware
func (sh *strictHandler) PostAssetsV1Folders(w http.ResponseWriter, r *http.Request) {
	var request PostAssetsV1FoldersRequestObject

	var body PostAssetsV1FoldersJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAssetsV1Folders(ctx, request.(PostAssetsV1FoldersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAssetsV1Folders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAssetsV1FoldersResponseObject); ok {
		if err := validResponse.VisitPostAssetsV1FoldersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAssetsV1UploadUrl operation middleware
func (sh *strictHandler) PostAssetsV1UploadUrl(w http.ResponseWriter, r *http.Request) {
	var request PostAssetsV1UploadUrlRequestObject

	var body PostAssetsV1UploadUrlJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAssetsV1UploadUrl(ctx, request.(PostAssetsV1UploadUrlRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAssetsV1UploadUrl")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAssetsV1UploadUrlResponseObject); ok {
		if err := validResponse.VisitPostAssetsV1UploadUrlResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbjW/bthL/Vwi+B6wp/J24awwMeI4Tp84SJ8v3shYDLZ1tthKpkVQcpcj//sAPyZKt",
	"JE6btmu3At0siuId746/+x3JfsQeDyPOgCmJOx+x9KYQEvOz64eUdaUEpZ98Kj1BQ8qI4kI3hCSKKJvo",
	"n2MaAO7g/9TnY9XdQHUzSl93qOAxD3wQD/e0Xe4qOBI8AqGSIQn14CqJQDdzBodj3PnjI/6vgPHjUu8q",
	"q/R0Ut/dVfD8085HTIJgBWlH8SigXibOaU7BmNETQBT4XWNFuCFhZIzVarTa1cbranPztPm6s/Gq016v",
	"NV+3r4yZREgU7mCfKKgqGmrbCSD+IQsS3FEihoq1RwdLJbQT7iqpnK3EeAu0tyJFOcMdvBMSGiA+RmoK",
	"iOj5odmUozgKOPHBN81j66K5gqbf/6hHSG3GReCvogP1i5NsuD/Vkv+kf/ITjmO6khypiIqNdR9yi3bI",
	"ie15V8HXIKQxR07B9r2yKFMw0SFxp7v8FVMBPu78gY1+Tnwl59u8/eey3mXj8dF78FQ+wtxaeGKMpcvj",
	"+4ky94UNMqv+9xJmzxgynxgpKfo+AfXsN4/Bng0n1zcTdWpU+IiBxaFWfVzA7Xd5v7lXSzbrmcnZOD2G",
	"v2KQZgLFaC0EzmIcHZofJEC55jSsSgJoEJIJSDTmwvSY8hAiMgHkEcFjCQGu4JDc7AObqCnuNBuNRonW",
	"zCSZRU106ilKRioN6IIO5bJa7XYFh5RlsksER0S/WRR8RAQwlcrUfdCLWAJ6i+tvsZmq4FytFXSoU2OI",
	"ZZ8shKOR6Ga8HHUVvCOETfALAMN9eAxwzac93fGugkOQkkyguFK7DMUMbiLwNCSA7o+458VCgF97VHWj",
	"w3zke7XvOV3TMB4wBYKRwE6tgvdpSNVhrA7HWzxmvrbZgF2TgPq9WEjTZchVX7/DFbwTRirZ4n4y7+ae",
	"uoGGgmTnhkplB4lida47EO3IVFw3VtPst15mQ67OXO7FFazT1Cnn+0RM9Ozs0hlyZeTiiguGrDlVa8hV",
	"1/GqcwsiPc7GAfWUG3PIlW6hIgQ/Z6t57OXyY85YETBfd6hgL/91Ltiz5pIx87jyGawxx6geo40LifHz",
	"eOMCk1s9Ib/L5p5Sx8XlwxSwOcBm1jSrth4ZgxdxqsS6C7g5H+WAUIamIDgaEcZAPBMczgXosat27NqS",
	"ss8JdGWYVs8pv8wF6W0JdGsvIP0KUYZGiTLAmA3cbGy8bv/8KkcJKFOvNvByLk9bHkm8WfK8q+BYBMv6",
	"9LaH6Ox4P/PLEt2eKhXJTr1O9FCyNidEdTLymq31R8HRvK0U4L1SCDtnKqtgGXYWIvq+CO7xmKmSVBmH",
	"IxA6WVIFoUQv9AQlIsx3zpVryKcCPBUk2iVqSmVJNm+XeeDeqH/W1P81s/lqifvJsfeEiLBuLIsCm5nu",
	"pW4LQFac6cHgYAfpETPWtBjmnwN3T6CJi2KfGR/1+MNSyngo6IRqrXQX5Gz+DWAUzaYgIDMGmtEgQCNA",
	"UnFhMvdTQLacQWZGKMLMQzElI85kSXaEm4gKkN0SYLmYAjPTiARIOmHgGxx1XxQmki92N1codkvdOvCX",
	"dRhs5wPLUnEDYLoasGzIvLUbKkVa/om16bJuXIR9CoFvDEZ8n9rwPyoY8uElhPtchGhsRkFqShQKY6l0",
	"WFDmBbEPvoVmQGEcKBoRoepabtUniqCjw5NTJCwu1NBpag2qJATjbCTi62ECIhWaUTV1VoPAN4sB/aS/",
	"+amWN9FH3LPhUz110J/DiCMeUC/BHQzJXgBvtiIv7DfIxWY8eM/pwftuMuw1ZgcnjZvD899uDm757GCb",
	"zw76nO739t6PWu0P5PI4GrXat4P30QiSPepfDMXV5W/0kO5Fv7f60/2L/q3XOm94yd7mfl/Sq8sdut8b",
	"fCCt8/aAzujBdnfm/irzfy1vuzvbP8215f4Ogoa8SPYC72QgB/R4e9RqN64u2o398+O2t3um9YpGF312",
	"dbI5G4UevTy5GQ3C4fWIHQcj9psa7Z7HV+vHfP9ybzoK/WBAZzf724PWwfudxnC7O7s8b27iCr6sdsPb",
	"ajeYcEHVNNSl1cXJRvXNQbdXPXnTbbVfZZ16AnxgipJA9/p10B0cnvQPt4fDn3cuuwdH+zv1VqO10Wg2",
	"N+uxrAKRqtqsy/U6mcmNP52/s8G2delrlpr54rTZ0gF8lb0/oRNGVCzM1s7I82HcbK1vtF/9/Hqz8dRn",
	"XMEfIFl1Dd2V4I5dkGdlhOwogxMT1xpTVLolOl/qipeSNM3Oqo6pyfUaCcktZ2Qmax4P64/ip4OZvHqF",
	"9V3J4eEymmrKC14sqEpONAWwC3/C+SSALSAChK43ddvIPPVTZNm7ONUc0HyDO+7tXFk9N20zO1KP8w8U",
	"0pEoM3WfbkqZRAfvHh7u7u/82T07ffOnHduNRCL6KyT4TqtK2ZgvG7/LUPdoYJJwSBiZUDZB1pylxDFN",
	"1oNet4tmMJJUgdktoMryQN3etd93jwa5bbUObtYaNRMcPAJGIoo7eN002VxqjOdId/26aUwJJWnoGJSg",
	"cK01QwGVSicEEgQPaU2UUVpG4NExBd/k5dpb9pa9fKkNq9ekZzYKOi9fvmVVZLbvUCxBSPTCgKfdRZUe",
	"j2ANCfCAXgMax6lc5IMiNJDoxXznz9Iv8zX1Kyjba8x+dlUF2Q3sNS3Ukv68VB6rcsEBDakCf1F2ruSf",
	"C9eDSGCSKv1lCIroHLL2lmHjCWHmrXMt3gVlXXfeND4RJAQFQppafZHm6ITCrQOc5ceCh/dtjpmw/SsG",
	"kcyj1pGX+Xq0e7iWTRfrgNKVvFTYmR0jIzbSgWwmdo9sL91dKpP2e2szvlrfm/pvDuTgTXDtn2yFo/Xz",
	"+Kq31SC7Z5Ori/6tv3ueDHbP2dXsl19WUe6A3CCWVWbOYoqjMShveo+SxssFHX0YkzhQuNNq5MBQP4Tk",
	"hoZx6Ph7SJl7KtkTf6dtbvmfWXOtRiNXThhOE0WBWxD199JS/rkSTylGT7kiQW7itiR11Ga56Gw2yqpO",
	"56xn9lFFM1AzIaPUSsVdLrURIUiin6dEDuFGHS3usBZOJEacB0DYUgIyKiyUgsUhS9LOEpnszoHQZkJ0",
	"DCoWTKIcGul1QeZgp9FjjnIVlMcO3ZWrKQhZ0zPceGKAPLoxXTaHLeJnlFYLbX8NoWfsA+MzhiSIaxB2",
	"F7xWSOwG+5YT8R/v9BJfTvWmXa8wGYchEYlF1Xx+IgoRu/OgxczzXX2UVOclZQCqpKTdNu2IMAf8o8Sm",
	"IJPOXNLiLEhqyPQ0uTwtRU3ZOSY0QFQvQySVbtDmJZTpfJkgmzm5QDIeudxZW0oSVoc0T2wlRxbFH8wW",
	"/VRJjXjmTNKo/wJqk1pFZ4sx5/URETV1o97i58gXrpDWRb6r7hcRehkFN0rYkcuveso+krHngZTa5Mk3",
	"WRipxZxLGVcIwkgla06b5tdYMRpDuKC34DupG19eqvWDnu+Yx8z/HgDCHqfj+3Aie13AioUFboqAMg6s",
	"MYWzbB2ZAslQHx0Xa0Vc+Jfm3k9zvwR8aUc8PwH+FED7HFpH0nPDFTjRAqexn67CW05TW/4IhOVfIHwW",
	"ppRBXyk7qrtNXhOwXJZAoztod7uqxG4eTYlEIwCWu2jH0cl6gTMt4cQRlwtA4cZ+Ml7Yveq/F9v5HHAY",
	"u4P1Fe99lmy6rQQP5uQ4u+PwN6Jf5kCJq3k0JaAqGvdtYqDSvLWx98Nzs35qjTkibTQ2v7xcd9XGBEhA",
	"vZQGzYhEIfftPt8oQYSZxJD6cO2H5Y4OnGx02si8D0QFRAHxoOruR5QDaZqRycJ5n861dnhdXzKYIWdG",
	"jXZuZA3jcEOlKUG1QsXqNDuxMkdVpqPZsDXHX/kVb1jjKsh8bOXaDfxPAOec6t81Tj8UqAtHvyUROz+J",
	"cacvqb+dbUJg6psibwm+Gty1x5+2OQuffyLy/ojAZmjhAgjlocZ4/yeZwpBcRD23lfUAZTR1qkY6jWZu",
	"c6X8zGhlwth3Qi0ygFTmoupzuabsandZgNipmDpcp0pXQS/B1d0S6jQ/hx1m19ZW/tc+iwwxu+X+OEfM",
	"TfHvwBF/dMwp3m/6BrTPOZzYC9+WPMgfl9SZuM528Rehzabp5+BxrlDOLoYu18eGtUUF98/p28NgeJa7",
	"XfEl4LB4UbLMa5bOpGxidRz85uxL02LLegbb/wLaVwa0fwKbmseaVe7Tt/O0GDOH0gsjgvuxZ1iI7eRu",
	"v+eu20c0f9ceL9+h2OeeuWR8XTZEp14P9Pspl6qz3mg06vju3d3/AwAA//+wqniqVT0AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
